version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - devops

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@test.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - devops

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER = admin
      - RABBITMQ_DEFAULT_PASS = admin1234
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
    networks:
      - devops

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - devops

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.8
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - devops

  catalog.api:
    image: catalogapi
    container_name: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5117
      - "ConnectionStrings__CatalogConnectionString=Server=postgres;Port=5432;Database=CatalogDb;User Id=admin;Password=admin1234;"
      - "ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "5117:5117"
    depends_on:
      - postgres
    networks:
      - devops

  search.api:
    image: searchapi
    container_name: search.api
    build:
      context: .
      dockerfile: Services/Search/Search.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5118
      - "ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration__Url=http://elasticsearch:9200"
      - "ElasticConfiguration__DefaultIndex=products-dev"
    ports:
      - "5118:5118"
    depends_on:
      - elasticsearch
    networks:
      - devops

volumes:
  postgres-data:
    external: false
  pgadmin-data:
    external: false
  rabbitmq-data:
    external: false
  elasticsearch-data:
    external: false

networks:
  devops:
