global using Xunit;
global using AutoMapper;
global using Catalog.API.Infrastructure;
global using Catalog.API.Infrastructure.DTOs;
global using Catalog.API.Infrastructure.Entities;
global using Catalog.API.Infrastructure.Exceptions;
global using Catalog.API.Infrastructure.Mapper;
global using Catalog.API.Services;
global using Microsoft.EntityFrameworkCore;
